export const styles = {
  app: {
    minHeight: "100vh",
    background: "var(--app-bg)",
    color: "var(--text-primary)",
    fontFamily: "'Space Grotesk', sans-serif",
    padding: "0 0 60px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "22px 28px",
    background: "var(--header-bg)",
    backdropFilter: "blur(10px)",
    borderBottom: "1px solid var(--border)",
  },
  brand: { display: "flex", alignItems: "center", gap: 8 },
  brandIcon: {
    width: 26, height: 26, borderRadius: 8, background: "var(--accent)",
    display: "flex", alignItems: "center", justifyContent: "center",
    boxShadow: "0 10px 18px rgba(47,111,237,0.28)",
  },
  ghostBtn: {
    display: "flex", alignItems: "center", gap: 4, background: "rgba(255,255,255,0.7)",
    border: "1px solid var(--border)", color: "var(--text-primary)",
    borderRadius: 999, padding: "8px 14px", fontSize: 13, cursor: "pointer",
    fontFamily: "'Space Grotesk', sans-serif",
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.06)",
  },
  hero: {
    padding: "48px 28px 0",
    backgroundImage: "radial-gradient(ellipse at 50% 0%, rgba(47,111,237,0.12), transparent 60%)",
    maxWidth: 980,
    margin: "0 auto",
  },
  heroText: { textAlign: "left", marginBottom: 18 },
  panel: {
    background: "var(--panel-bg)",
    border: "1px solid var(--border)",
    borderRadius: 22,
    padding: 22,
    boxShadow: "0 20px 60px rgba(15, 23, 42, 0.08)",
  },
  fieldRow: { display: "flex", alignItems: "flex-end", gap: 8, marginBottom: 14 },
  field: { flex: 1 },
  label: {
    display: "flex", alignItems: "center", gap: 5, fontSize: 11, color: "var(--text-muted)",
    marginBottom: 6, letterSpacing: 0.5, fontFamily: "'JetBrains Mono', monospace",
  },
  select: {
    width: "100%", background: "var(--input-bg)", border: "1px solid var(--border)",
    color: "var(--text-primary)", borderRadius: 12, padding: "10px 12px", fontSize: 14,
    fontFamily: "'Space Grotesk', sans-serif", outline: "none",
    boxShadow: "inset 0 1px 1px rgba(16,33,58,0.03)",
  },
  swapBtn: {
    width: 34, height: 34, borderRadius: "50%", background: "var(--accent)", border: "none",
    display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer",
    marginBottom: 2, flexShrink: 0,
    boxShadow: "0 8px 20px rgba(47,111,237,0.24)",
  },
  stepper: {
    display: "flex", alignItems: "center", gap: 12, background: "var(--input-bg)",
    border: "1px solid var(--border)", borderRadius: 12, padding: "8px 14px", width: "fit-content",
  },
  stepBtn: {
    width: 20, height: 20, borderRadius: 6, border: "1px solid rgba(16,33,58,0.08)",
    background: "var(--panel-bg)", color: "var(--text-primary)", cursor: "pointer", fontSize: 14, lineHeight: 1,
  },
  primaryBtn: {
    width: "100%", background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-2) 100%)", color: "var(--text-on-accent)", border: "none",
    borderRadius: 12, padding: "13px 20px", fontWeight: 700, fontSize: 14.5, cursor: "pointer",
    fontFamily: "'Space Grotesk', sans-serif", marginTop: 4,
    boxShadow: "0 12px 22px rgba(47,111,237,0.28)",
  },
  section: { maxWidth: 760, margin: "0 auto", padding: "10px 28px 0" },
  boardHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 14 },
  board: {
    background: "var(--panel-bg)", border: "1px solid var(--border)", borderRadius: 16,
    overflow: "hidden", boxShadow: "0 14px 32px rgba(15, 23, 42, 0.06)",
  },
  boardColHeader: {
    display: "flex", padding: "10px 18px", fontSize: 10.5, color: "var(--text-muted)",
    letterSpacing: 1, fontFamily: "'JetBrains Mono', monospace",
    borderBottom: "1px solid var(--border)", background: "var(--header-bg)",
  },
  row: {
    display: "flex", alignItems: "center", padding: "16px 18px",
    borderBottom: "1px solid rgba(16,33,58,0.05)", borderLeft: "2px solid transparent",
    background: "var(--panel-bg)",
  },
  mutedText: { color: "var(--text-muted)" },
  monoText: { fontFamily: "'JetBrains Mono', monospace" },
  monoMutedText: { fontFamily: "'JetBrains Mono', monospace", color: "var(--text-muted)" },
  accentText: { color: "var(--accent)" },
  accentMonoText: { fontFamily: "'JetBrains Mono', monospace", color: "var(--accent)", fontWeight: 700 },
  tablePriceWrap: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 6 },
  seatsBadge: {
    display: "inline-flex", alignItems: "center", justifyContent: "center",
    fontSize: 10.5, fontFamily: "'JetBrains Mono', monospace", color: "var(--text-on-accent)",
    background: "rgba(47,111,237,0.12)", border: "1px solid rgba(47,111,237,0.24)",
    borderRadius: 999, padding: "4px 8px", lineHeight: 1.2,
  },
  selectBtn: {
    background: "transparent", border: "1px solid var(--accent)", color: "var(--accent)",
    borderRadius: 999, padding: "6px 16px", fontSize: 12.5, fontWeight: 600, cursor: "pointer",
    fontFamily: "'Space Grotesk', sans-serif",
  },
  seatPanel: {
    background: "var(--panel-bg)", border: "1px solid var(--border)", borderRadius: 16,
    padding: "24px 20px", display: "flex", flexDirection: "column", alignItems: "center",
    boxShadow: "0 16px 36px rgba(15, 23, 42, 0.05)",
  },
  planeNose: {
    fontSize: 10, letterSpacing: 3, color: "var(--text-muted)", marginBottom: 18,
    fontFamily: "'JetBrains Mono', monospace",
  },
  seatRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 8 },
  seatRowNum: { width: 18, fontSize: 11, color: "var(--text-muted)", fontFamily: "'JetBrains Mono', monospace" },
  seat: {
    width: 32, height: 32, borderRadius: 8, border: "1px solid", fontSize: 12,
    fontFamily: "'JetBrains Mono', monospace", fontWeight: 600,
  },
  legend: { display: "flex", gap: 18, marginTop: 18, flexWrap: "wrap", justifyContent: "center" },
  legendItem: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "var(--text-muted)" },
  legendDot: { width: 12, height: 12, borderRadius: 4, border: "1px solid", display: "inline-block" },
  summaryBar: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    marginTop: 18, background: "var(--input-bg)", border: "1px solid var(--border)",
    borderRadius: 16, padding: "16px 20px",
  },
  ticket: {
    display: "flex", background: "var(--panel-bg)", border: "1px solid var(--border)",
    borderRadius: 20, overflow: "hidden", boxShadow: "0 20px 60px rgba(15, 23, 42, 0.08)",
  },
  ticketMain: { flex: 1, padding: 26 },
  ticketGrid: {
    display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16, marginTop: 26,
    paddingTop: 20, borderTop: "1px dashed rgba(16,33,58,0.12)",
  },
  ticketLabel: { fontSize: 10.5, color: "var(--text-muted)", letterSpacing: 0.5, fontFamily: "'JetBrains Mono', monospace", marginBottom: 4 },
  ticketVal: { fontSize: 14, fontWeight: 600 },
  ticketStub: {
    width: 190, background: "var(--input-bg)", padding: 26, borderLeft: "1px dashed rgba(16,33,58,0.12)",
    display: "flex", flexDirection: "column", justifyContent: "center",
  },
  toast: {
    position: "fixed",
    top: 20,
    right: 20,
    zIndex: 20,
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "linear-gradient(135deg, rgba(14,34,61,0.9) 0%, rgba(23,58,93,0.9) 100%)",
    color: "var(--toast-text)",
    borderRadius: 16,
    padding: "12px 14px",
    boxShadow: "0 18px 40px rgba(9, 20, 35, 0.18)",
    border: "1px solid rgba(255,255,255,0.1)",
    maxWidth: 360,
  },
  toastIcon: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "var(--success)",
    color: "var(--on-success)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 14,
    flexShrink: 0,
  },
  toastTitle: {
    fontWeight: 700,
    fontSize: 13,
    marginBottom: 2,
  },
  toastText: {
    fontSize: 12,
    color: "rgba(245,249,255,0.8)",
    lineHeight: 1.4,
  },
};
